<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CMPay.Domain\CMPay.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net09.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
